name: Update Phishing URLs

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-phishing-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Use stored secret for authentication

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Fetch Latest Phishing URLs
        run: |
          curl -s https://openphish.com/feed.txt -o phishing_urls.txt
          git add phishing_urls.txt
          git commit -m "Updated phishing URLs list from OpenPhish"
          git push origin main  # Push changes
