name: Update Phishing URLs

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  update-phishing-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest phishing URLs
        run: curl -X GET "https://openphish.com/feed.txt" -o phishing_urls.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add phishing_urls.txt
          git commit -m "Updated phishing URLs list"
          git push
